### ISSUE TITLE
OTA for ESP8266

### ISSUE THREAD

**Issue by iBobik** [pfalcon/pycopy#37]
Over-the-air updates are [documented only for WiPy](https://pycopy.readthedocs.io/en/latest/wipy/general.html#upgrading-the-firmware-over-the-air), but Micropython can do it [also for ESP8266](http://micropython.org/download#esp8266).

Was this removed in Pycopy or it just is not documented yet?

**Comment by pfalcon** [comment]
Nothing like that was removed. If you see something missing in Pycopy docs comparing to MicroPython docs, please give exact details/links. (For example, lately I spotted missing "Differences" chapter and fixed it.)

Otherwise, many things aren't documented in details, on MicroPython's side first of all. Note that Pycopy's focus is (for the foreseeable future) is the device-independent *language*, not adaptations to a particular device, so things like that would need to be fixed upstream.
