### ISSUE TITLE
Naming confusion in repl for baremetal ports

### ISSUE THREAD

**Issue by st42** [pfalcon/pycopy#43]
This isn't an issue but it may be an oversight. You have forked micropython and renamed it pycopy but whenever you enter repl it still shows micropython
`MicroPython v3.0.0 on 2020-01-24; ESP32 module with ESP32`
Is this intentional or did you just forget to change it? In my opinion the firmware should reflect the name of the fork it came from. I know this is cosmetic and doesn't affect functionality, but if you put this much work into changes and additions it should bear it's proper name.

BTW I love pycopy and am using it in a project I designed. Its a water sensor that beeps loudly and sends notifications through Pushover to all my devices when water in my basement isn't draining properly.

**Comment by pfalcon** [comment]
Thanks for the report. Indeed, I updated the name in the banner for unix port, but overlooked doing that for baremetal ports. Now done.

Otherwise, there's more things to references to rename/update throughout, but I indeed don't haste doing them "en masse", to avoid the situation when a fork made a big changes delta in naming and then ran out of steam. Instead, my idea to update naming gradually, together with other changes. So again, thanks for pointing this case.
